[package]
name = "beeconfig"
version = "0.1.0"
edition = "2021"

[lib]
name = "beeconfig"
path = "src/lib.rs"

[dependencies]
confy = "0.6"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
